travis:
  secure:
    BINSTAR_TOKEN: q7yx6AKhffmRGRgED4Z0z5NSGktp3H98q+y7TqLnJMrX6DHx251vIr+lY857HKTRMRO8TGCZAyWfy3ceTMwP4VPdzU0dQWz2+l9G7mY/1i4B15mZ6rHTFXJCJ5TE4siiOZrDev3vX8XWEbHg/+fb9DkugvgBKN/12bHBOCercuwKzGwPUMJFg76w5bbWIVY7wjODURM4p07u+lU06pjz3G/sx5oG0q13j+GVn4rByBRDAOwXOMUKPotf4I2K6gDUMPcYFO//GiJ2EvsNTqs5qDHQXI61ypKJIbX9kaw6A4DbrAYQrG9Z9FzMWR2lBFnhcdMQn3AXSHUhyb2YbNU1EdFajnR7I5mCfvxLHWmWudQsYdipS5M6pgsY/TtYpqLAK3WvE8gOyL7XKImAmfp8+C17KlQm9w5t79h1N3Z/7f1A+SvLbNxf/vA7vgfU3lJuAEETEVljLCqlAQjkfvebQ6ywtwhy+HjdjXB7Y3P3VTRDHmJqitHwcuJYK4b8+dh7SuWkjyQQRjUOtVAJPPcKXBgQMKsSP1RNNzJ225v3kYWdsBIQKtqXz4uuueKuCPC0yyMXchy0POTifdR9aFhKQwyGZLsN+AgT+/5gkeFbwdv1lH711rBFkNrjTClc4scJDHKhTN/jTcNKWXFy6+cJ6DTnyAY2FepccGhtzV8KUyE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
