travis:
  secure:
    BINSTAR_TOKEN: uhJs5+kp2ZLannSIOgIPgWYTlSO/pl/PIyjZ4UCaEygZhh9C0y75jUIMNS2Jg8mXMG0pAlikASum4vPWnIl+M1uzLs0nSJGPqg6WqhRpE2OBF5ilop+CaGzxa1pqsFXdt2sC083Fg1JtseHZpnA3PfiTl6zbEVl9kePGR+DD7PhTBJLOqeKUF0USwsl8rGJoFuXfyxEuvgywqOoRCBgirJIbskxDM4RwRVKHW/icK4cudGoGiM+du2wtUloOkd1cc2foveBM8x1ue9GeREmAYl4a0HmlW9Og0oA7S4nzmI376h5iF62SUMlwsnZ3Q/Dgw4QbRnjBu/LWXwEqc43pt8GC7y5e2wnXgVH8fRwJlMp4VKwIrBgPuY3X70adgaApbiI8VHgJXEyxcgdYZoiPq3L98Q5HyTvreefx8hQ+/eyEUZwfaonfP6cRYGJwKiKF608GcSlpJW6X6vfg0e+wAzRegZyluyCiXGTPw0WM5B9+XPC1uKbdHiiHR2dbc1awuIgcERSoPWUY6vpW+oEvibcG2/qXc9NS8W81H9FrW7LVVg1d5LLARZhhRiC/Ekb6cDt1iGZa76sYn1VfRNQvhRZAwOnHb/RmgStf9zBDDKNv0dNGhQ4OnVwHih5Xurosx6HsSOGshfNy5OB7/ZSZ+Auck+HClv1KKkZpmGUIcWc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
