travis:
  secure:
    BINSTAR_TOKEN: dl++JmwoNFCEqrPskpqWu6peW8myHp9mLFXu8LTiDX2qbUfZOQ99ptZCKvia7ixYTqmw/AFbpvhtv+svuaQ/byG3Fz5SOI+OSEbZSlLlL7in+XahUF6Viy4PrIsqV7KxNgxbMShVr4zrryOSTNrcvpbAwtdlPxh5x1dcUB/xBg0r5IFQjKYHK79p3kvq1bBcUa1NGra2UOxk2rKju4EzeXkFpEexqziB2I/2wGn38QlHsM+wKfSaznXA6RXU4r4j7lzrtCwiETZOOY5U2P7XYgwRwtXGUZ/MYn07/REsInka15fmidsZmd+DfvuNO2uZkd2udGqWkQpMqQQn7POqHJshjyfpXZLyinIBmvNHnAT9/61SR8hU75nVZVBW2nDrqOArdK9ZCKj8kRKGo0DyN0Xvd7yNvgFE3QgRUNNvRUqJ0nOYq/iiji1pBtl470TlWk41M9PPEFQt68hBdJ3+L149EWcx84Xh24Rjn3ORGXp4KMlHhKnM+Esc6J+JPBfsvhJ/i4boYcmPUeEjfeGzy1uYa/zSEDeJFYF9MnuJb4ysQUF+dIbdDNJjHatAVAxLxQsT/62rf1BqG0WI5h0aLYySvsX4pMyPNu0rf8PHX9+TyhwRSZtPN6SWYvMXZn7VyWKIaLnGWJ3Wjm9JYqWWG99FPlUWQ7ERLGqKV0IxqI0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
