travis:
  secure:
    BINSTAR_TOKEN: OwWfjG/Wdwk4FFtmS+HQh66RuiKOs0rhSUUHgKILaR+U/BUzO3Y4CgbqMgYikc21Ny2Ge86333A3GS41Rc47me4ZC3PJgDv3EYJLe6dUy7IWquq7/cSm05rxYLDzlvDaY5/UCryOuzoskg/KsOK9e8wrhBPwy3Fbi0YtPCVTEMybxvUR2NXiZU0MllQL5uhuDx73DQAsBG10eHv+jBVL0kzZ1im+Y2ktVGK1TwzYEulvjmu0jaoU9UAwrMsFepRZSsS6WtrPOUDT+qhuu1lUXLJ5LPyYVp07zZ0TggOLamC0yKqx5J4fm9zONnZlj3ssxoJtYcjuV+6TDZzqSI2gl1e2ywiR4sAp/rMx1HsernTAT3YorU5tgL0I1Y8HDFNPrD/y+GxDsHwv8P3dffl5Rqa1kNNodlGIOG6Gv8V2a/3TkO+JYiUXnWpMh49PR1/B7tbqSpamk2+FqEwJeCoY6sWcZLFD18wfi1FDmR2vw+ZQHMmm4Y/+uhAKnBEaCeu/D9kifgAWSFMqeV7DKDQGxEiRqd/a4G+nXsZQDT++uRsoXOCPvV/q5wU0Beg23mIpB6zAdHO+mVoCZIG/s5zdwYVMfifTpHgSa4baiwb/yVls8l5JomW4jxVA+dTX8ooULvLy5FDk5eRp9RnAZ+XTWRut/SLweQpX4gV8qQShzYs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
